Create CrossChainBalance.md
tellor-io/dataSpecs pull request #86
Opened 2022-11-18 19:24 UTC by themandalore

2022-11-18 21:27 UTC, tkernell commented on types/CrossChainBalance.md
> +
add `blockNumber`

2022-11-18 21:36 UTC, tkernell commented
this looks good

2022-11-19 13:07 UTC, oraclown requested changes
Thanks @themandalore

2022-11-19 13:07 UTC, oraclown commented on types/CrossChainBalance.md
> +1. **chainId** (string): ID of the proposal.
`uint256`? Remove "ID of the proposal"

2022-11-19 13:07 UTC, oraclown commented on types/CrossChainBalance.md
> +1. **contractAddress** (string): ID of the proposal.
`address`. Remove "ID of the proposal"

2022-11-19 13:07 UTC, oraclown commented on types/CrossChainBalance.md
> +abi.encode("CrossChainBalance", abi.encode(1,0x88dF592F8eb5D7Bd38bFeF7dEb0fBc02cf3778a0,15998590))
to be more clear:
```c
queryData = abi.encode("CrossChainBalance", abi.encode(1,0x88dF592F8eb5D7Bd38bFeF7dEb0fBc02cf3778a0,15998590))
```
?

2022-11-22 15:38 UTC, oraclown requested changes
Minor type fixes needed

2022-11-22 15:38 UTC, oraclown commented on types/CrossChainBalance.md
> +1. **chainId** (string):
change type from string to uint256

2022-11-22 15:38 UTC, oraclown commented on types/CrossChainBalance.md
> +2. **contractAddress** (string):
change type from string to address

2022-11-22 15:38 UTC, oraclown commented on types/CrossChainBalance.md
> +3. **blockNumber** (string):
change type from string to uint256

2022-11-22 16:01 UTC, themandalore commented on types/CrossChainBalance.md
> +3. **blockNumber** (string):
done

2022-11-23 02:59 UTC, merged